### ISSUE TITLE
Problem opening files through file browser in Mac OS X

### ISSUE THREAD

**Issue by JuanCasanovaSdweb** [exelearning/iteexe#209] opened 2017-08-28 07:32 UTC
Related to #198.

Opening a file through OS X's file browser when eXe is already open doesn't work.

**Comment by Javiobcn** [comment] 2022-01-11 14:13
If you exit from eXe from the menu file - exit, then the browser can be closed and everything works fine, the problem is close the browser directly, then the eXe app stays running without a browser... 

If the browser has been closed and it is no longer possible to exit correctly, we will see that there is an eXe icon on the MAC taskbar, what we have to do is close it there, right click and "force exit"

I have detected that on Mac when you close the browser "badly" the app that remains on the taskbar, it ends up disappearing after approx. 4 or 5 minutes without activity ...

**Closed by Javiobcn** 2022-01-11 14:13 UTC
Labels: D, Accepted
