### ISSUE TITLE
Windows installation problem: Error opening DLL for writing

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#178] opened 2017-04-04 20:01 UTC
I've seen this message 3 times in different computers and networks while installing 2.1.2. Windows 7 in all cases. 

![exe_install_error](https://cloud.githubusercontent.com/assets/2928868/24676136/15c14e42-1982-11e7-8be6-52ee7745f1b9.gif)

One of them had eXe 2.0.4. The other one didn't have eXe, but I used the ready to run version on it before. 

Everything seems to work after retrying, but we should try to fix that if possible.

**Comment by JuanCasanovaSdweb** [comment] 2017-08-01 07:37
We haven't been able to reproduce it. It's probably caused due to a false positive in Avast (paid version).

**Comment by JuanCasanovaSdweb** [comment] 2017-09-28 11:17
Closing for now, if it happens again let us know!

**Closed by JuanCasanovaSdweb** 2017-09-28 11:17 UTC
Labels: Works for me
